version: 2

sources:
  - name: raw_data
    schema: dados_brutos
    tables:
      - name: cliente_info
        description: "Tabela de clientes com mais informações"
      - name: clientes
        description: "Tabela de clientes"
